#!/usr/bin/env bash


declare -r DIR=$(dirname ${BASH_SOURCE[0]})

# get related env variables
[[ -f ${DIR}/.env ]] && . ${DIR}/.env

echo $BASE64APPTOKEN
echo

# res=$(curl -s \
#                 -H "Authorization: Basic $BASE64APPTOKEN" \
#                 -d grant_type=refresh_token \
#                 -d refresh_token="$REFRESH_TOKEN" \
#                 https://accounts.spotify.com/api/token)

# echo "$res" | jq

# ACCESS_TOKEN="AQCdAJgcH-L4GjObQGSyQbwhD5U7vcuT6gR4LfgZfVT_WzNsg66NQE8Djv8LvuO_vgjetXjOrpD8-dvJyKB4FSN1DEqLlKQuvMTrDkN31f_Xc8tEDT7IiSNp5xr9o1NgqdQOaqgUVA2Z7ZgFFS5otktd2d5p7xICoMbpdoXIzanXq2Avvy3C7_lDLnrmz_CxwpxPJcH9pZpgDDOQ_WdNLjCkvfNCuqAYsyiqLPzv-IOIrvbIhc_D12klmzWf9ejiszbgzI2i6ukee4l_aEs4y7wvfLUKs7lgcukgxQGa6_IdQg"

# player=$(curl -s -X \
#         GET "https://api.spotify.com/v1/me/player" \
#         -H "Authorization: Bearer $ACCESS_TOKEN")

# echo "$player"


res=$(curl -s \
            -H "Authorization: Basic $BASE64APPTOKEN" \
            -d grant_type=authorization_code \
            -d code="$ACCESS_CODE" \
            -d redirect_uri=http://localhost \
            https://accounts.spotify.com/api/token)


echo "$res"


{
    "access_token":"BQDFcWCzwXF0X8sXOs23j8oldnjurVUt0VFs4zIzOwAiSRipf1JXsTIbfB2nT1enOwlswXIoN9EF0Sz8FdoTDrygeaSxgMrRNe73zzH2V7WaQACYDVmFkLx110DdV42MKwzQfvjK_4zgIGVPjhPcFhCgLQQs",
    "token_type":"Bearer",
    "expires_in":3600,
    "refresh_token":"AQC5FfeqFY6xFSRT4a39-oxI2zs9MIV5OXy-MPabqaPMrwdgLBiGt1Z2uo81iBeGjclQ6CWcj5U5YvaNII87fQOz5FQyKMWQE4qubQAqPnIJMdXwa6_fOEz-5vUGlcyWQ6g",
    "scope":"user-modify-playback-state user-read-playback-state user-read-currently-playing user-read-recently-played"
}

